---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: mcsps-k3s-clients
  name: mcsps-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edit
subjects:
- name: mcsps-edit@default
  kind: User
  apiGroup: rbac.authorization.k8s.io
